#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#include "debug_uart/bsp_debug_uart.h"
#include "bsp_esp8266/bsp_wifi_esp8266.h"
#include "circle_buf.h"
#include "cJSON_handle.h"
#include "stdlib.h"
#include "Systick.h"
#include "Key.h"
#include "Relay.h"
#include "uart_hlw.h"
#include <time.h>   // 用于 srand()

uint32_t last_report = 0;
extern PowerStrip_t g_strip;
uint8_t g_force_upload_flag = 0; // 全局标志位
/* 按键按下标志 */
extern volatile bool key1_sw2_press;
extern volatile bool key2_sw3_press ;
extern circle_buf_t g_BL0942_rx_buf;
extern volatile bool g_uart3_rx_end;
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

void hal_entry(void)
{
    /* TODO: add your own code here */
    Debug_UART0_Init(); // SCI0 UART 调试串口初始化
	SystickInit();
	Key_IRQ_Init();
	uart_hlw_init();
	
	circlebuf_init();
	BL0942_circlebuf_init();
	
	// 1. 初始化随机数种子（可以用系统滴答定时器的值）
    // 在 hal_entry.c 中
     srand(HAL_GetTick()); // 现在绝对不会报错了，因为 HAL_GetTick 已经有了明确的声明
	


    // 2. 默认先把插座全部打开，方便观察测试
    for(int i=0; i<4; i++) {
        g_strip.sockets[i].on = true;
    }
	
	ESP8266_MQTT_Test();

    while(1)
	{
		 Simulation_Random_Load_Test();
		
		// 1. 随时解析串口进来的 JSON 指令
		handle_uart_json_stream();

		// 3s 定时或被标志位触发
        if((HAL_GetTick() - last_report >= 3000) || g_force_upload_flag) 
        {
            g_force_upload_flag = 0; // 清除标志
            
            // 更新电参并上报
            g_strip.voltage = 220.0f + (rand()%10)/10.0f;
            upload_strip_status();
            
            last_report = HAL_GetTick();
        }
		
		
//		if (g_uart3_rx_end == 1)
//        {
//            g_uart3_rx_end = 0;
//            
//            Data_Processing(g_BL0942_rx_buf.buffer,0);
//            BL0942_circlebuf_clear();
//           
//        }
//		
//		if (key1_sw2_press)
//        {
//            key1_sw2_press = false; //标志位清零
//			sw_ctrl(true);
//			printf("key0 is pressed\r\n");
//			g_ioport.p_api->pinWrite(g_ioport.p_ctrl,BSP_IO_PORT_01_PIN_02,BSP_IO_LEVEL_LOW);
//        }

//		  /* 判断按键 KEY2_SW3 是否被按下 */
//		 if (key2_sw3_press)
//		{
//				key2_sw3_press = false; //标志位清零
//				sw_ctrl(false);
//				printf("key1 is pressed\r\n");
//			    g_ioport.p_api->pinWrite(g_ioport.p_ctrl,BSP_IO_PORT_01_PIN_02,BSP_IO_LEVEL_HIGH);
//		}
//		
//		  Send_com();
//		  R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);

				
    }
        
       
	
}


    
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif




/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
